# Generated by Django 4.0.4 on 2023-03-29 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="message",
            field=models.TextField(default="prueba"),
            preserve_default=False,
        ),
    ]
