# Generated by Django 4.0.4 on 2022-05-12 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0002_auto_20220307_0441"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoffeeBag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=200)),
                (
                    "species",
                    models.CharField(
                        choices=[("Ar", "Arábiga"), ("Ro", "Robusta")],
                        default="Ar",
                        max_length=2,
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("26", "Sonora"),
                            ("10", "Durango"),
                            ("03", "Baja California Sur"),
                            ("04", "Campeche"),
                            ("16", "Michoacán de Ocampo"),
                            ("31", "Yucatán"),
                            ("19", "Nuevo León"),
                            ("12", "Guerrero"),
                            ("11", "Guanajuato"),
                            ("25", "Sinaloa"),
                            ("15", "Ciudad de México"),
                            ("29", "Tlaxcala"),
                            ("13", "Hidalgo"),
                            ("08", "Chihuahua"),
                            ("24", "San Luis Potosí"),
                            ("27", "Tabasco"),
                            ("23", "Quintana Roo"),
                            ("28", "Tamaulipas"),
                            ("14", "Jalisco"),
                            ("05", "Coahuila de Zaragoza"),
                            ("09", "Ciudad de México"),
                            ("21", "Puebla"),
                            ("06", "Colima"),
                            ("02", "Baja California"),
                            ("32", "Zacatecas"),
                            ("01", "Aguascalientes"),
                            ("22", "Querétaro"),
                            ("30", "Veracruz de Ignacio de la Llave"),
                            ("20", "Oaxaca"),
                            ("17", "Morelos"),
                            ("18", "Nayarit"),
                            ("07", "Chiapas"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="shop",
            name="roaster",
            field=models.BooleanField(default=False),
        ),
    ]
