# Generated by Django 4.0.4 on 2022-05-12 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0004_alter_coffeebag_species"),
    ]

    operations = [
        migrations.AddField(
            model_name="coffeebag",
            name="coffee_shop",
            field=models.ManyToManyField(related_name="product", to="shops.shop"),
        ),
    ]
