# Generated by Django 4.0.4 on 2022-05-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_coffeebag_coffee_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='rating',
            field=models.DecimalField(choices=[('0', 0), ('0.5', 0.5), ('1', 1), ('1.5', 1.5), ('2', 2), ('2.5', 2.5), ('3.0', 3), ('3.5', 3.5), ('4', 4), ('4.5', 4.5), ('5', 5)], decimal_places=1, default='0', max_digits=1),
        ),
    ]
