# Generated by Django 4.0.4 on 2022-05-14 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0009_shop_created_date_shop_modified_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
