# Generated by Django 4.0.4 on 2022-05-15 21:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0010_shop_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop",
            name="content",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
