# Generated by Django 4.0.4 on 2023-04-06 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_review_shop_alter_review_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='recommended',
            field=models.BooleanField(),
        ),
    ]
